"""Added input fields for questions 6-14

Revision ID: 02eaff5639d1
Revises: 0ffed41152ab
Create Date: 2025-05-07 23:57:20.979681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02eaff5639d1'
down_revision = '0ffed41152ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screen_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('work_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('study_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('social_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alcohol', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wake_up_time', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('transportation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bed_time', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('bed_time')
        batch_op.drop_column('mood')
        batch_op.drop_column('transportation')
        batch_op.drop_column('wake_up_time')
        batch_op.drop_column('alcohol')
        batch_op.drop_column('social_time')
        batch_op.drop_column('study_time')
        batch_op.drop_column('work_time')
        batch_op.drop_column('screen_time')

    # ### end Alembic commands ###
