"""Add money_spent field to UserData

Revision ID: fcd004af49fa
Revises: 02eaff5639d1
Create Date: 2025-05-08 21:04:13.321872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd004af49fa'
down_revision = '02eaff5639d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('money_spent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('money_spent')

    # ### end Alembic commands ###
